### ISSUE TITLE
Fix SMS reply error

### ISSUE THREAD

**Issue by adamskt** [IntelliTect/text-trolley-hackathon2022#50]
`Connection id "0HMOT0NPS2U5M", Request id "0HMOT0NPS2U5M:00000001": An unhandled exception was thrown by the application.
2023-03-04T23:15:47.854873098Z       System.ArgumentException: Invalid type parameter 'Twilio.AspNet.Core.TwiMLResult' specified for 'ActionResult<T>'.
2023-03-04T23:15:47.854884898Z          at Microsoft.AspNetCore.Mvc.ActionResult`1..ctor(ActionResult result)
2023-03-04T23:15:47.854888398Z          at Microsoft.AspNetCore.Mvc.ActionResult`1.op_Implicit(ActionResult result)
2023-03-04T23:15:47.854891198Z          at IntelliTect.TextTrolley.Web.Api.MessagingController.ReceiveMessage(SmsRequest inboundRequest) in /home/runner/work/text-trolley-hackathon2022/text-trolley-hackathon2022/src/IntelliTect.TextTrolley.Web/Api/MessagingController.cs:line 40
2023-03-04T23:15:47.854894098Z          at lambda_method156(Closure, Object)
2023-03-04T23:15:47.854904398Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
2023-03-04T23:15:47.855207797Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
2023-03-04T23:15:47.855214297Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2023-03-04T23:15:47.855217597Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
2023-03-04T23:15:47.855220397Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
2023-03-04T23:15:47.855223497Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2023-03-04T23:15:47.855226597Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2023-03-04T23:15:47.855229597Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
2023-03-04T23:15:47.855232397Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
2023-03-04T23:15:47.855235297Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2023-03-04T23:15:47.855238297Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
2023-03-04T23:15:47.855241197Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
2023-03-04T23:15:47.855243997Z          at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
2023-03-04T23:15:47.855247097Z          at Program.<>c.<<<Main>$>b__0_5>d.MoveNext() in /home/runner/work/text-trolley-hackathon2022/text-trolley-hackathon2022/src/IntelliTect.TextTrolley.Web/Program.cs:line 170`

**Comment by twofingerrightclick** [comment]
#54
